import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapProvider from "@/components/BootstrapProvider"; // 추가

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Board ParaDice",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BootstrapProvider> {/* BootstrapProvider로 감싸기 */}
            {children}
        </BootstrapProvider>
        </body>
        </html>
    );
}
