import BootstrapProvider from "@/components/BootstrapProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SonnerToaster } from "@/components/ui/sonner"; // ✅ SonnerToaster import
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Board ParaDice",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ko" suppressHydrationWarning> 
        <head>
            <meta charSet="utf-8"/>
            <title>Board ParaDice</title>
            <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/pretendard@latest/dist/web/static/pretendard.css"/>
        </head>
        <body>

        <SonnerToaster /> {/* ✅ Toast 메시지 활성화 */}
        <BootstrapProvider> {/* ✅ BootstrapProvider 적용 */}
            <ThemeProvider >
            {children}
            </ThemeProvider>
        </BootstrapProvider>
        </body>
        </html>
    );
}
