name: CI Pipeline

on:
  push:
    #브랜치 추가하려면 밑에 써주면 됨
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

          # 인스톨
      - name: Install Dependencies
        run: npm install

        #빌드
      - name: Build Project
        run: npm run build

        #테스트
      - name: Run Tests
        run: npm test
